### PR TITLE
Add Ports information to the expanded view

### PR DESCRIPTION
**Pull request by kenan-rhoton**
For a project I'm working, it's very practical to be able to see which ports are open/exposed, so I've made this "dirty" implementation to see them within the expanded view (I felt they cluttered the compact view way too much).

I think some variation of this could be a useful addition to ctop, perhaps adding an option to disable/enable it ("p" key?).

Feel free to completely drop the request if it's not in line with the project.

### CODE REVIEW

**Comment by bcicen** [comment]
Thanks for the PR @kenan-rhoton.

`Container` does already allow for abritrary metadata from inspect to be saved via `SetMeta()` [like so](https://github.com/bcicen/ctop/blob/master/dockersource.go#L70),  which can then be displayed in the Expanded Info table.

This approach also prevents the Docker API from being overrun with extraneous inspect requests.

**Comment by kenan-rhoton** [comment]
I seem to recall that Ports information doesn't appear on inspect... But I may be wrong, will check it out.

**Comment by kenan-rhoton** [comment]
You were right, it appears in inspect, I think this solution is MUCH better (we could even keep the ports information on all the time, since they have such a small footprint in the expanded view)

**Comment by bcicen** [comment]
:+1: looks great. I'll push an update shortly to cleanup multi-line metadata values in expanded view as well.

**Comment by bcicen** [comment]
fyi, pushed https://github.com/bcicen/ctop/commit/58d5fba9459d41fe437183d86d03b9acb9dc501d to update the port info formatting and add `HostIP`:
portinfo

**Comment by kenan-rhoton** [comment]
Oh nice, it looks awesome!

**Pull request merged**
