### PR TITLE
#135 Add uptime column

### PR DESCRIPTION
**Pull request by stokito**
#135 Added uptime column and info row

### CODE REVIEW

**Comment by jtagcat** [comment]
It seems that the merged commit has poofed at some point, uptime isn't present either..? cc @bcicen

**Comment by stokito** [comment]
it's not released yet

**Comment by jtagcat** [comment]
It's merged to master, the only branch, and there have been multiple releases since.

**Comment by stokito** [comment]
Don't worry the commit a603c1b58c3454574b44b2dad2f4741414b544d7 is merged to master

**Pull request merged**
