### PR TITLE
Use go-runewidth to increment x in TextView

### PR DESCRIPTION
**Pull request by garsue**
This PR fixes rendering wide-width characters in TextView.
When running the following container, ctop shows incomplete logs.

```
docker container run debian:buster yes こんにちは
```
image

`TextView` always renders characters as single width. So wide-width characters hide the next character.
[go-runewidth](https://github.com/mattn/go-runewidth) fixes this problem.

image

### CODE REVIEW

**Comment by stokito** [comment]
shouldn't the runewidth be added into go.mod file?

**Comment by garsue** [comment]
> shouldn't the runewidth be added into go.mod file?

go.mod looks like already includes.
https://github.com/bcicen/ctop/blob/0094cba5eaebcf478282655b1de7a8605cdbf3a9/go.mod#L9

But after building this PR, some diffs appear in go.sum.
Should I also commit them?

**Comment by stokito** [comment]
I don’t know, I guess not necessary.

**Comment by garsue** [comment]
I pushed it. It is not necessary but it is annoying in development.
Maybe we should do `go mod tidy` to clean up dependencies.

**Comment by bcicen** [comment]
merged; thanks @garsue !!

**Pull request merged**
