### PR TITLE
add support for alternative navigation

### LINKED ISSUE #120: Suggestion for alternative navigation
Thanks for a great app! I use it all the time. However I've always secretly been hoping someone would update it with the following keybindings.

Right arrow - Show logs
Left arrow - Details view (single view)
Enter - Action menu... Stop, restart, exec, etc.

### PR DESCRIPTION
**Pull request by xiechengsheng**
Signed-off-by: xiechengsheng <XIE1995@whut.edu.cn>

Fix #120 
In fact, the `single view` and `log view` hot keys already exist in codes, so we just change this hot keys to left/right.

### CODE REVIEW

**Comment by bcicen** [comment]
left/right navigation can be added, but I don't see any reason to remove the existing `l` and `o` keybindings.

**Comment by xiechengsheng** [comment]
@bcicen  OK, I have updated codes right now, PTAL.

**Comment by bcicen** [comment]
thank you; merged!

**Pull request merged**
